namespace UrbanPlanToolbox.Views;

public sealed class PlanningCalculatorPage;
public sealed class UnitScaleConverterPage;
public sealed class ColorPaletteRecorderPage;
public sealed class InspirationManagementPage;
public sealed class HomePage;
public sealed class CommonToolsPage;
public sealed class DesignToolsPage;
public sealed class ResearchToolsPage;
public sealed class ProjectArchivePage;
public sealed class AboutPage;
public sealed class WorkflowReviewChecklistPage;
public sealed class RegulationsIndexPage;
public sealed class DesignConceptDictionaryPage;
public sealed class CoordinateSystemConverterPage;
public sealed class PlanningTerminologyPage;
public sealed class FieldSurveyPhotoGisPage;
public sealed class DrawingComparisonPage;
public sealed class CoordinateBatchFormatConverterPage;
