using Microsoft.UI.Xaml.Data;
using UrbanPlanToolbox.Services;

namespace UrbanPlanToolbox.Views;

public sealed class ReferenceFilterLabelConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, string language) =>
        ReferenceFilterTaxonomy.Localize(value?.ToString());

    public object ConvertBack(object value, Type targetType, object parameter, string language) => value;
}

internal static class ReferenceFilterTaxonomy
{
    private sealed record Label(string Japanese, string English);

    private static readonly IReadOnlyDictionary<string, Label> Labels = new Dictionary<string, Label>(StringComparer.Ordinal)
    {
        // Regions and jurisdictions.
        ["中国"] = new("中国", "China"),
        ["日本"] = new("日本", "Japan"),
        ["美国"] = new("米国", "United States"),
        ["欧盟/欧洲"] = new("EU・欧州", "EU / Europe"),
        ["中国/方法术语"] = new("中国／方法用語", "China / methodological term"),
        ["中国概念/国际传播"] = new("中国概念／国際発信", "Chinese concept / international communication"),
        ["通用"] = new("一般", "General"),
        ["通用/中国制度色彩较强"] = new("一般／中国制度の文脈が強い", "General / strong Chinese institutional context"),
        ["通用/分类标准不同"] = new("一般／分類基準が異なる", "General / classification standards differ"),
        ["通用/政策理念"] = new("一般／政策理念", "General / policy concept"),
        ["通用/政策语境不同"] = new("一般／政策文脈が異なる", "General / policy contexts differ"),
        ["通用/日本常用"] = new("一般／日本で一般的", "General / common in Japan"),
        ["通用/日本政策语境较强"] = new("一般／日本の政策文脈が強い", "General / strong Japanese policy context"),
        ["通用/标准术语"] = new("一般／標準用語", "General / standards terminology"),
        ["通用/标准语境"] = new("一般／標準文脈", "General / standards context"),
        ["通用/法规计算口径可能不同"] = new("一般／法規上の算定基準が異なる場合あり", "General / regulatory calculation basis may differ"),
        ["通用/法规语境有差异"] = new("一般／法規文脈に差異", "General / regulatory context differs"),
        ["通用/译法依语境"] = new("一般／訳語は文脈依存", "General / translation depends on context"),
        ["通用/语境依赖"] = new("一般／文脈依存", "General / context dependent"),

        // Planning terminology categories.
        ["GIS与空间研究"] = new("GIS・空間研究", "GIS & spatial research"),
        ["中国国土空间制度"] = new("中国国土空間制度", "China territorial spatial planning system"),
        ["交通与街道"] = new("交通・街路", "Transport & streets"),
        ["城市设计与更新"] = new("都市デザイン・更新", "Urban design & renewal"),
        ["开发指标"] = new("開発指標", "Development metrics"),
        ["日本国土与都市计划制度"] = new("日本の国土・都市計画制度", "Japan national land & urban planning system"),
        ["生态韧性防灾"] = new("生態・レジリエンス・防災", "Ecology, resilience & disaster prevention"),
        ["规划基础"] = new("計画基礎", "Planning fundamentals"),

        // Design-concept project types.
        ["交通枢纽"] = new("交通結節点", "Transit hub"),
        ["交通规划"] = new("交通計画", "Transport planning"),
        ["公共服务"] = new("公共サービス", "Public services"),
        ["公共空间"] = new("公共空間", "Public space"),
        ["商业街区"] = new("商業街区", "Commercial district"),
        ["城市更新"] = new("都市更新", "Urban renewal"),
        ["城市设计"] = new("都市デザイン", "Urban design"),
        ["基础设施"] = new("インフラ", "Infrastructure"),
        ["工业遗产"] = new("産業遺産", "Industrial heritage"),
        ["建筑设计"] = new("建築設計", "Architectural design"),
        ["总体规划"] = new("総合計画", "Master planning"),
        ["慢行系统"] = new("歩行・自転車ネットワーク", "Active-mobility network"),
        ["文旅策划"] = new("文化・観光企画", "Culture & tourism planning"),
        ["旧城改造"] = new("旧市街地再生", "Historic-area renewal"),
        ["景观规划"] = new("ランドスケープ計画", "Landscape planning"),
        ["校园规划"] = new("キャンパス計画", "Campus planning"),
        ["片区改造"] = new("地区再生", "District regeneration"),
        ["片区更新"] = new("地区更新", "District renewal"),
        ["生态修复"] = new("生態修復", "Ecological restoration"),
        ["社区更新"] = new("コミュニティ更新", "Community renewal"),
        ["社区营造"] = new("まちづくり", "Community placemaking"),
        ["社区规划"] = new("コミュニティ計画", "Community planning"),
        ["站城一体"] = new("駅まち一体開発", "Station-area integration"),
        ["综合开发"] = new("複合開発", "Mixed-use development"),
        ["街道改造"] = new("街路改修", "Street retrofit"),
        ["街道设计"] = new("街路設計", "Street design"),
        ["道路设计"] = new("道路設計", "Road design"),

        // Design-concept tags.
        ["临时性"] = new("一時性", "Temporary"),
        ["低成本"] = new("低コスト", "Low cost"),
        ["低扰动"] = new("低負荷", "Low disruption"),
        ["低速"] = new("低速", "Low speed"),
        ["催化"] = new("触媒作用", "Catalytic"),
        ["公交"] = new("公共交通", "Transit"),
        ["公共交通"] = new("公共交通", "Public transport"),
        ["共享"] = new("共有", "Shared"),
        ["再利用"] = new("再利用", "Reuse"),
        ["分期"] = new("段階整備", "Phasing"),
        ["半室外"] = new("半屋外", "Semi-outdoor"),
        ["参与"] = new("参加", "Participation"),
        ["可达性"] = new("アクセシビリティ", "Accessibility"),
        ["场所感"] = new("場所性", "Sense of place"),
        ["复合功能"] = new("複合用途", "Mixed functions"),
        ["存量"] = new("既存ストック", "Existing stock"),
        ["存量更新"] = new("既存ストック更新", "Existing-stock renewal"),
        ["安全"] = new("安全", "Safety"),
        ["小尺度"] = new("小規模", "Small scale"),
        ["恢复"] = new("回復", "Recovery"),
        ["昼夜使用"] = new("昼夜利用", "Day-night use"),
        ["步行"] = new("歩行", "Walking"),
        ["活力"] = new("活力", "Vitality"),
        ["活动"] = new("活動", "Activity"),
        ["混合开发"] = new("複合開発", "Mixed-use development"),
        ["渐进"] = new("段階的", "Incremental"),
        ["渐进式"] = new("段階的", "Incremental"),
        ["生境"] = new("生息地", "Habitat"),
        ["生态"] = new("生態", "Ecology"),
        ["生活圈"] = new("生活圏", "Daily-life area"),
        ["紧凑"] = new("コンパクト", "Compact"),
        ["节点"] = new("拠点", "Node"),
        ["蓝绿"] = new("ブルー・グリーン", "Blue-green"),
        ["触媒"] = new("触媒", "Catalyst"),
        ["试验"] = new("実験", "Pilot"),
        ["边界"] = new("境界", "Boundary"),
        ["过渡"] = new("移行", "Transition"),
        ["连续性"] = new("連続性", "Continuity"),
        ["连通性"] = new("連結性", "Connectivity"),
        ["遗产"] = new("遺産", "Heritage"),
        ["门户"] = new("ゲートウェイ", "Gateway"),
        ["集约"] = new("集約", "Intensive use"),
        ["雨洪"] = new("雨水・洪水", "Stormwater"),
        ["韧性"] = new("レジリエンス", "Resilience"),
        ["风险"] = new("リスク", "Risk"),
        ["骑行"] = new("自転車", "Cycling"),

        // Regulations topics.
        ["ADA公共设施"] = new("ADA公共施設", "ADA public accommodations"),
        ["ADA州地方政府"] = new("ADA州・地方政府", "ADA state and local governments"),
        ["HUD无障碍"] = new("HUDアクセシビリティ", "HUD accessibility"),
        ["HUD环境审查"] = new("HUD環境審査", "HUD environmental review"),
        ["一张图"] = new("統合一図管理", "Integrated One Map"),
        ["专业资格"] = new("専門資格", "Professional qualifications"),
        ["乡村规划"] = new("農村計画", "Rural planning"),
        ["乡镇总体规划"] = new("郷鎮総合計画", "Township master planning"),
        ["企业资质"] = new("企業資格", "Enterprise qualifications"),
        ["优良住宅"] = new("優良住宅", "Quality housing"),
        ["低层住宅"] = new("低層住宅", "Low-rise housing"),
        ["住宅"] = new("住宅", "Housing"),
        ["住宅瑕疵"] = new("住宅瑕疵", "Housing defects"),
        ["住宅质量"] = new("住宅品質", "Housing quality"),
        ["住房政策"] = new("住宅政策", "Housing policy"),
        ["体检评估"] = new("都市診断・評価", "Urban examination & assessment"),
        ["保护线管理"] = new("保護ライン管理", "Protection-line management"),
        ["全国规划"] = new("全国計画", "National planning"),
        ["公共采购"] = new("公共調達", "Public procurement"),
        ["公寓管理"] = new("マンション管理", "Condominium management"),
        ["公平住房"] = new("公正住宅", "Fair housing"),
        ["公用事业采购"] = new("公益事業調達", "Utility procurement"),
        ["农业地域"] = new("農業地域", "Agricultural areas"),
        ["分区规划"] = new("ゾーニング計画", "Zoning planning"),
        ["勘察设计"] = new("調査・設計", "Survey & design"),
        ["历史保护"] = new("歴史的環境保全", "Historic preservation"),
        ["历史保护程序"] = new("歴史的環境保全手続", "Historic preservation procedures"),
        ["历史文化"] = new("歴史・文化", "History & culture"),
        ["历史文化保护"] = new("歴史文化保全", "Historic & cultural preservation"),
        ["县级总体规划"] = new("県級総合計画", "County master planning"),
        ["双评价"] = new("双評価", "Dual evaluation"),
        ["可再生能源"] = new("再生可能エネルギー", "Renewable energy"),
        ["可航水域"] = new("可航水域", "Navigable waters"),
        ["园林绿化"] = new("園林緑化", "Landscaping & greening"),
        ["国土利用"] = new("国土利用", "National land use"),
        ["国土形成"] = new("国土形成", "National spatial formation"),
        ["国土空间规划体系"] = new("国土空間計画体系", "Territorial spatial planning system"),
        ["国家标准库"] = new("国家標準データベース", "National standards database"),
        ["土地与用途管制"] = new("土地・用途規制", "Land & use control"),
        ["土地区划整理"] = new("土地区画整理", "Land readjustment"),
        ["土地实施"] = new("土地施策", "Land implementation"),
        ["地下空间"] = new("地下空間", "Underground space"),
        ["地方条例"] = new("地方条例", "Local ordinances"),
        ["地质灾害"] = new("地質災害", "Geological hazards"),
        ["城乡规划"] = new("城郷計画", "Urban-rural planning"),
        ["城市公园"] = new("都市公園", "Urban parks"),
        ["城市绿地"] = new("都市緑地", "Urban green space"),
        ["城市规划"] = new("都市計画", "Urban planning"),
        ["城市规划实施"] = new("都市計画実施", "Urban planning implementation"),
        ["城市规划编制"] = new("都市計画策定", "Urban plan preparation"),
        ["基础设施控制"] = new("インフラ規制", "Infrastructure control"),
        ["密集市街地"] = new("密集市街地", "Densely built-up areas"),
        ["岩土工程"] = new("地盤工学", "Geotechnical engineering"),
        ["工业排放"] = new("産業排出", "Industrial emissions"),
        ["工程合同与物权"] = new("建設契約・物権", "Construction contracts & property rights"),
        ["工程监理"] = new("工事監理", "Construction supervision"),
        ["工程质量"] = new("工事品質", "Construction quality"),
        ["市政设施"] = new("都市施設", "Municipal infrastructure"),
        ["市级总体规划"] = new("市級総合計画", "Municipal master planning"),
        ["废弃物"] = new("廃棄物", "Waste"),
        ["建筑与工程"] = new("建築・建設", "Architecture & construction"),
        ["建筑产品"] = new("建設製品", "Construction products"),
        ["建筑基本"] = new("建築基本", "Building fundamentals"),
        ["建筑审查"] = new("建築審査", "Building review"),
        ["建筑师制度"] = new("建築士制度", "Architect system"),
        ["建筑技术"] = new("建築技術", "Building technology"),
        ["建筑抗震"] = new("建築耐震", "Building seismic design"),
        ["建筑能效"] = new("建築エネルギー性能", "Building energy performance"),
        ["建筑节能"] = new("建築省エネルギー", "Building energy conservation"),
        ["建筑防水"] = new("建築防水", "Building waterproofing"),
        ["建筑防火"] = new("建築防火", "Building fire safety"),
        ["开发许可"] = new("開発許可", "Development permission"),
        ["强制性规范体系"] = new("強制規範体系", "Mandatory code system"),
        ["征收搬迁"] = new("収用・移転", "Expropriation & relocation"),
        ["征收补偿"] = new("収用補償", "Expropriation compensation"),
        ["成员国建筑与规划法"] = new("加盟国建築・計画法", "Member-state building & planning law"),
        ["房地产"] = new("不動産", "Real estate"),
        ["房地产开发"] = new("不動産開発", "Real estate development"),
        ["执业资格"] = new("職業資格", "Professional licensure"),
        ["抗洪"] = new("洪水防御", "Flood protection"),
        ["抗震改修"] = new("耐震改修", "Seismic retrofit"),
        ["抗震规划"] = new("耐震計画", "Seismic planning"),
        ["抗震设计"] = new("耐震設計", "Seismic design"),
        ["抗震防灾"] = new("耐震防災", "Seismic disaster prevention"),
        ["招标投标"] = new("入札", "Tendering & bidding"),
        ["控制性详细规划"] = new("規制的詳細計画", "Regulatory detailed planning"),
        ["政府采购"] = new("政府調達", "Government procurement"),
        ["施工图审查"] = new("施工図審査", "Construction drawing review"),
        ["施工安全"] = new("施工安全", "Construction safety"),
        ["施工许可"] = new("施工許可", "Construction permit"),
        ["无障碍"] = new("バリアフリー", "Accessibility"),
        ["既有建筑"] = new("既存建築", "Existing buildings"),
        ["景观"] = new("景観", "Landscape"),
        ["暖通空调"] = new("HVAC", "HVAC"),
        ["木结构"] = new("木構造", "Timber structures"),
        ["材料试验"] = new("材料試験", "Material testing"),
        ["村镇建设"] = new("村鎮建設", "Village & town development"),
        ["标准检索"] = new("標準検索", "Standards search"),
        ["森林空间"] = new("森林空間", "Forest space"),
        ["水务与蓝线"] = new("水務・ブルーライン", "Water affairs & blue-line control"),
        ["水域湿地"] = new("水域・湿地", "Waters & wetlands"),
        ["水域许可"] = new("水域許可", "Water permit"),
        ["水环境"] = new("水環境", "Water environment"),
        ["水系控制"] = new("水系管理", "Water-system control"),
        ["河川"] = new("河川", "Rivers"),
        ["河道管理"] = new("河道管理", "River channel management"),
        ["洪水风险"] = new("洪水リスク", "Flood risk"),
        ["洪泛区"] = new("氾濫原", "Floodplain"),
        ["活动房屋"] = new("製造住宅", "Manufactured housing"),
        ["流域规划"] = new("流域計画", "Watershed planning"),
        ["测绘与GIS"] = new("測量・GIS", "Surveying & GIS"),
        ["海岸规划"] = new("沿岸計画", "Coastal planning"),
        ["海洋空间"] = new("海洋空間", "Marine spatial planning"),
        ["消防"] = new("消防", "Fire safety"),
        ["消防审验"] = new("消防審査・検査", "Fire design review & acceptance"),
        ["混凝土结构"] = new("コンクリート構造", "Concrete structures"),
        ["港湾"] = new("港湾", "Ports & harbors"),
        ["燃气"] = new("ガス", "Gas"),
        ["物业住房"] = new("不動産管理・住宅", "Property & housing"),
        ["物业维护"] = new("建物維持管理", "Property maintenance"),
        ["环境保护"] = new("環境保護", "Environmental protection"),
        ["环境噪声"] = new("環境騒音", "Environmental noise"),
        ["环境评价"] = new("環境評価", "Environmental assessment"),
        ["生产绿地"] = new("生産緑地", "Productive green space"),
        ["生命安全"] = new("生命安全", "Life safety"),
        ["生态保护"] = new("生態保護", "Ecological protection"),
        ["生态空间"] = new("生態空間", "Ecological space"),
        ["用地分类"] = new("用地分類", "Land-use classification"),
        ["电气"] = new("電気", "Electrical"),
        ["盛土安全"] = new("盛土安全", "Fill safety"),
        ["省级总体规划"] = new("省級総合計画", "Provincial master planning"),
        ["砌体结构"] = new("組積造", "Masonry structures"),
        ["空气质量"] = new("大気質", "Air quality"),
        ["空置房"] = new("空き家", "Vacant housing"),
        ["空间数据"] = new("空間データ", "Spatial data"),
        ["竣工备案"] = new("竣工届出", "Completion filing"),
        ["紧凑城市"] = new("コンパクトシティ", "Compact city"),
        ["结构作用"] = new("構造作用", "Structural actions"),
        ["结构荷载"] = new("構造荷重", "Structural loads"),
        ["结构设计基础"] = new("構造設計基礎", "Basis of structural design"),
        ["给排水"] = new("給排水", "Water supply & drainage"),
        ["综合建筑"] = new("総合建築", "General building"),
        ["绿地控制"] = new("緑地規制", "Green-space control"),
        ["绿色建筑"] = new("グリーンビルディング", "Green building"),
        ["联邦住宅节能"] = new("連邦住宅省エネ", "Federal residential energy efficiency"),
        ["联邦土地"] = new("連邦土地", "Federal lands"),
        ["联邦建筑无障碍"] = new("連邦建築アクセシビリティ", "Federal building accessibility"),
        ["联邦建筑节能"] = new("連邦建築省エネ", "Federal building energy efficiency"),
        ["联邦资助无障碍"] = new("連邦補助アクセシビリティ", "Federal-aid accessibility"),
        ["能源效率"] = new("エネルギー効率", "Energy efficiency"),
        ["自动喷水"] = new("自動スプリンクラー", "Automatic sprinklers"),
        ["自然保护"] = new("自然保護", "Nature conservation"),
        ["自然公园"] = new("自然公園", "Natural parks"),
        ["行业标准库"] = new("業界標準データベース", "Industry standards database"),
        ["行政许可"] = new("行政許可", "Administrative permits"),
        ["规划环评"] = new("計画環境アセスメント", "Planning environmental assessment"),
        ["规划资质"] = new("計画資格", "Planning qualifications"),
        ["详细规划"] = new("詳細計画", "Detailed planning"),
        ["质量保修"] = new("品質保証", "Quality warranty"),
        ["道路"] = new("道路", "Roads"),
        ["采用情况"] = new("採用状況", "Adoption status"),
        ["野火风险"] = new("山火事リスク", "Wildfire risk"),
        ["钢混组合结构"] = new("鋼・コンクリート合成構造", "Steel-concrete composite structures"),
        ["钢结构"] = new("鋼構造", "Steel structures"),
        ["铝结构"] = new("アルミ構造", "Aluminum structures"),
        ["项目环评"] = new("事業環境アセスメント", "Project environmental assessment"),
        ["鸟类保护"] = new("鳥類保護", "Bird protection")
    };

    public static string Localize(string? value)
    {
        if (string.IsNullOrWhiteSpace(value) || !Labels.TryGetValue(value, out var label)) return value ?? string.Empty;
        var language = LocalizationService.Default.CurrentLanguage;
        if (language.StartsWith("ja", StringComparison.OrdinalIgnoreCase)) return label.Japanese;
        if (language.StartsWith("en", StringComparison.OrdinalIgnoreCase)) return label.English;
        return value;
    }
}
