using System.Globalization;
using UrbanPlanToolbox.Models;

namespace UrbanPlanToolbox.Services;

public static class WebDavLocalization
{
    public static string Get(string language, string key)
    {
        var locale = language.StartsWith("ja", StringComparison.OrdinalIgnoreCase) ? "ja" :
            language.StartsWith("en", StringComparison.OrdinalIgnoreCase) ? "en" : "zh";
        return (locale, key) switch
        {
            ("ja", "Title") => "WebDAV クラウドアーカイブ",
            ("en", "Title") => "WebDAV cloud archive",
            (_, "Title") => "WebDAV 云存档",
            ("ja", "Description") => "既存の安全なバックアップ処理でアップロード・復元し、認証情報は Windows Credential Locker に保存します。",
            ("en", "Description") => "Upload and restore through the existing safe backup flow; credentials are stored in Windows Credential Locker.",
            (_, "Description") => "使用已有安全备份流程上传与恢复；凭据由 Windows Credential Locker 保存。",
            ("ja", "StatusLabel") => "状態",
            ("en", "StatusLabel") => "Status",
            (_, "StatusLabel") => "状态",
            ("ja", "NotConfigured") => "未設定",
            ("en", "NotConfigured") => "Not configured",
            (_, "NotConfigured") => "未配置",
            ("ja", "Configured") => "接続先: {0} · {1}",
            ("en", "Configured") => "Connected to {0} · {1}",
            (_, "Configured") => "已连接：{0} · {1}",
            ("ja", "ConnectedNoBackup") => "接続済み · アーカイブ未作成",
            ("en", "ConnectedNoBackup") => "Connected · no archive yet",
            (_, "ConnectedNoBackup") => "已连接 · 尚未备份",
            ("ja", "ConnectedLastBackup") => "接続済み · 最終バックアップ {0}",
            ("en", "ConnectedLastBackup") => "Connected · last backup {0}",
            (_, "ConnectedLastBackup") => "已连接 · 上次备份 {0}",
            ("ja", "CredentialMissing") => "認証情報がありません。接続設定をやり直してください。",
            ("en", "CredentialMissing") => "Credentials are missing. Configure the connection again.",
            (_, "CredentialMissing") => "凭据缺失，请重新配置连接。",
            ("ja", "LastBackupNever") => "クラウドアーカイブ: まだありません",
            ("en", "LastBackupNever") => "Cloud archive: none yet",
            (_, "LastBackupNever") => "云存档：尚未创建",
            ("ja", "LastBackup") => "最終クラウドアーカイブ: {0}",
            ("en", "LastBackup") => "Last cloud archive: {0}",
            (_, "LastBackup") => "上次云存档：{0}",
            ("ja", "Configure") => "設定",
            ("en", "Configure") => "Configure",
            (_, "Configure") => "配置",
            ("ja", "BackupNow") => "今すぐ保存",
            ("en", "BackupNow") => "Back up now",
            (_, "BackupNow") => "立即备份",
            ("ja", "RestoreFromCloud") => "クラウドから復元",
            ("en", "RestoreFromCloud") => "Restore from cloud",
            (_, "RestoreFromCloud") => "从云端恢复",
            ("ja", "RestorePickerTitle") => "復元するクラウドアーカイブを選択",
            ("en", "RestorePickerTitle") => "Choose a cloud archive to restore",
            (_, "RestorePickerTitle") => "选择要恢复的云存档",
            ("ja", "Manage") => "アーカイブ管理",
            ("en", "Manage") => "Manage archives",
            (_, "Manage") => "管理存档",
            ("ja", "ConfigureTitle") => "WebDAV 接続設定",
            ("en", "ConfigureTitle") => "WebDAV connection",
            (_, "ConfigureTitle") => "WebDAV 连接设置",
            ("ja", "ServerUrl") => "WebDAV サーバー URL",
            ("en", "ServerUrl") => "WebDAV server URL",
            (_, "ServerUrl") => "WebDAV 服务器地址",
            ("ja", "Username") => "ユーザー名",
            ("en", "Username") => "Username",
            (_, "Username") => "用户名",
            ("ja", "Password") => "パスワード / アプリパスワード",
            ("en", "Password") => "Password / app password",
            (_, "Password") => "密码 / 应用专用密码",
            ("ja", "PasswordExisting") => "空欄の場合は保存済みの認証情報を使用します。",
            ("en", "PasswordExisting") => "Leave blank to keep the saved credential.",
            (_, "PasswordExisting") => "留空可继续使用当前已保存凭据。",
            ("ja", "RemotePath") => "リモートフォルダー",
            ("en", "RemotePath") => "Remote folder",
            (_, "RemotePath") => "远端目录",
            ("ja", "TestSave") => "接続テストして保存",
            ("en", "TestSave") => "Test & save",
            (_, "TestSave") => "测试并保存",
            ("ja", "Disconnect") => "接続解除",
            ("en", "Disconnect") => "Disconnect",
            (_, "Disconnect") => "断开连接",
            ("ja", "TestSuccess") => "WebDAV 接続を確認し、設定を安全に保存しました。",
            ("en", "TestSuccess") => "WebDAV connection verified and saved securely.",
            (_, "TestSuccess") => "WebDAV 连接测试成功，设置已安全保存。",
            ("ja", "OperationFailed") => "WebDAV 操作に失敗しました: {0}",
            ("en", "OperationFailed") => "WebDAV operation failed: {0}",
            (_, "OperationFailed") => "WebDAV 操作失败：{0}",
            ("ja", "BackupSuccess") => "クラウドアーカイブをアップロードし、リモート上の存在を確認しました。",
            ("en", "BackupSuccess") => "Cloud archive uploaded and verified on the remote server.",
            (_, "BackupSuccess") => "云存档已上传，并完成远端存在性校验。",
            ("ja", "ManageTitle") => "WebDAV クラウドアーカイブ",
            ("en", "ManageTitle") => "WebDAV cloud archives",
            (_, "ManageTitle") => "WebDAV 云存档",
            ("ja", "NoBackups") => "クラウドアーカイブはまだありません。",
            ("en", "NoBackups") => "No cloud archives yet.",
            (_, "NoBackups") => "云端暂无存档。",
            ("ja", "NoBackupsAfterCreate") => "以前の作成時刻は記録されていますが、現在のリモートフォルダーに .uptbackup が見つかりません。もう一度作成してください。",
            ("en", "NoBackupsAfterCreate") => "A previous archive time is recorded, but no .uptbackup file is visible in the current remote folder. Create a new archive again.",
            (_, "NoBackupsAfterCreate") => "已记录过云存档时间，但当前远端目录中未发现 .uptbackup 文件，请重新创建云存档。",
            ("ja", "Restore") => "復元",
            ("en", "Restore") => "Restore",
            (_, "Restore") => "恢复",
            ("ja", "Delete") => "削除",
            ("en", "Delete") => "Delete",
            (_, "Delete") => "删除",
            ("ja", "Close") => "閉じる",
            ("en", "Close") => "Close",
            (_, "Close") => "关闭",
            ("ja", "RestoreConfirmTitle") => "クラウドアーカイブから復元しますか？",
            ("en", "RestoreConfirmTitle") => "Restore from cloud archive?",
            (_, "RestoreConfirmTitle") => "从云存档恢复？",
            ("ja", "RestoreConfirm") => "現在のローカルデータは復元前に安全バックアップされ、その後このクラウドアーカイブで置き換えられます。",
            ("en", "RestoreConfirm") => "Current local data will be safety-backed up before it is replaced by this cloud archive.",
            (_, "RestoreConfirm") => "当前本地数据会先生成安全备份，随后由所选云存档替换。",
            ("ja", "DeleteConfirmTitle") => "クラウドアーカイブを削除しますか？",
            ("en", "DeleteConfirmTitle") => "Delete cloud archive?",
            (_, "DeleteConfirmTitle") => "删除云存档？",
            ("ja", "DeleteConfirm") => "この操作はリモートの {0} を削除します。元に戻せません。",
            ("en", "DeleteConfirm") => "This permanently deletes {0} from the remote server.",
            (_, "DeleteConfirm") => "这将永久删除远端文件 {0}，无法撤销。",
            ("ja", "RestoreSuccess") => "クラウドアーカイブから復元しました。",
            ("en", "RestoreSuccess") => "Cloud archive restored successfully.",
            (_, "RestoreSuccess") => "已从云存档成功恢复。",
            ("ja", "DeleteSuccess") => "クラウドアーカイブを削除しました。",
            ("en", "DeleteSuccess") => "Cloud archive deleted.",
            (_, "DeleteSuccess") => "云存档已删除。",
            ("ja", "HttpWarning") => "HTTP 接続では認証情報が暗号化されません。HTTPS の使用を推奨します。",
            ("en", "HttpWarning") => "HTTP does not encrypt WebDAV credentials. HTTPS is strongly recommended.",
            (_, "HttpWarning") => "HTTP 不会加密 WebDAV 凭据，强烈建议使用 HTTPS。",
            _ => key
        };
    }

    public static string Format(string language, string key, params object[] args) => string.Format(CultureInfo.CurrentCulture, Get(language, key), args);

    public static string StatusText(string language, CloudBackupStatus status, string? errorCode) =>
        Format(language, "OperationFailed", string.IsNullOrWhiteSpace(errorCode) ? status.ToString() : $"{status} / {errorCode}");
}