using System.Globalization;
using UrbanPlanToolbox.Models;

namespace UrbanPlanToolbox.Services;

public static class WebDavLocalization
{
    public static string Get(string language, string key)
    {
        var locale = language.StartsWith("ja", StringComparison.OrdinalIgnoreCase) ? "ja" :
            language.StartsWith("en", StringComparison.OrdinalIgnoreCase) ? "en" : "zh";
        return (locale, key) switch
        {
            ("ja", "Title") => "WebDAV クラウドアーカイブ",
            ("en", "Title") => "WebDAV cloud archive",
            (_, "Title") => "WebDAV 云存档",
            ("ja", "Description") => "既存の .uptbackup を自分の WebDAV ストレージへ保存・復元します。ローカルデータは引き続き主データです。",
            ("en", "Description") => "Store and restore standard .uptbackup snapshots in your own WebDAV storage. Local data remains authoritative.",
            (_, "Description") => "将标准 .uptbackup 快照保存到你自己的 WebDAV 存储并可安全恢复，本地数据仍是主数据源。",
            ("ja", "NotConfigured") => "未設定",
            ("en", "NotConfigured") => "Not configured",
            (_, "NotConfigured") => "未配置",
            ("ja", "Configured") => "接続先: {0} · {1}",
            ("en", "Configured") => "Connected to {0} · {1}",
            (_, "Configured") => "已连接：{0} · {1}",
            ("ja", "CredentialMissing") => "認証情報がありません。接続設定をやり直してください。",
            ("en", "CredentialMissing") => "Credentials are missing. Configure the connection again.",
            (_, "CredentialMissing") => "凭据缺失，请重新配置连接。",
            ("ja", "LastBackupNever") => "クラウドアーカイブ: まだありません",
            ("en", "LastBackupNever") => "Cloud archive: none yet",
            (_, "LastBackupNever") => "云存档：尚未创建",
            ("ja", "LastBackup") => "最終クラウドアーカイブ: {0}",
            ("en", "LastBackup") => "Last cloud archive: {0}",
            (_, "LastBackup") => "上次云存档：{0}",
            ("ja", "Configure") => "接続設定",
            ("en", "Configure") => "Connection settings",
            (_, "Configure") => "连接设置",
            ("ja", "BackupNow") => "今すぐクラウド保存",
            ("en", "BackupNow") => "Create cloud archive",
            (_, "BackupNow") => "立即创建云存档",
            ("ja", "Manage") => "クラウドアーカイブを管理",
            ("en", "Manage") => "Manage cloud archives",
            (_, "Manage") => "管理云存档",
            ("ja", "ConfigureTitle") => "WebDAV 接続設定",
            ("en", "ConfigureTitle") => "WebDAV connection",
            (_, "ConfigureTitle") => "WebDAV 连接设置",
            ("ja", "ServerUrl") => "WebDAV サーバー URL",
            ("en", "ServerUrl") => "WebDAV server URL",
            (_, "ServerUrl") => "WebDAV 服务器地址",
            ("ja", "Username") => "ユーザー名",
            ("en", "Username") => "Username",
            (_, "Username") => "用户名",
            ("ja", "Password") => "パスワード / アプリパスワード",
            ("en", "Password") => "Password / app password",
            (_, "Password") => "密码 / 应用专用密码",
            ("ja", "PasswordExisting") => "空欄の場合は保存済みの認証情報を使用します。",
            ("en", "PasswordExisting") => "Leave blank to keep the saved credential.",
            (_, "PasswordExisting") => "留空可继续使用当前已保存凭据。",
            ("ja", "RemotePath") => "リモートフォルダー",
            ("en", "RemotePath") => "Remote folder",
            (_, "RemotePath") => "远端目录",
            ("ja", "TestSave") => "接続テストして保存",
            ("en", "TestSave") => "Test & save",
            (_, "TestSave") => "测试并保存",
            ("ja", "Disconnect") => "接続解除",
            ("en", "Disconnect") => "Disconnect",
            (_, "Disconnect") => "断开连接",
            ("ja", "TestSuccess") => "WebDAV 接続を確認し、設定を安全に保存しました。",
            ("en", "TestSuccess") => "WebDAV connection verified and saved securely.",
            (_, "TestSuccess") => "WebDAV 连接测试成功，设置已安全保存。",
            ("ja", "OperationFailed") => "WebDAV 操作に失敗しました: {0}",
            ("en", "OperationFailed") => "WebDAV operation failed: {0}",
            (_, "OperationFailed") => "WebDAV 操作失败：{0}",
            ("ja", "BackupSuccess") => "クラウドアーカイブを作成しました。",
            ("en", "BackupSuccess") => "Cloud archive created successfully.",
            (_, "BackupSuccess") => "云存档创建成功。",
            ("ja", "ManageTitle") => "WebDAV クラウドアーカイブ",
            ("en", "ManageTitle") => "WebDAV cloud archives",
            (_, "ManageTitle") => "WebDAV 云存档",
            ("ja", "NoBackups") => "クラウドアーカイブはまだありません。",
            ("en", "NoBackups") => "No cloud archives yet.",
            (_, "NoBackups") => "云端暂无存档。",
            ("ja", "Restore") => "復元",
            ("en", "Restore") => "Restore",
            (_, "Restore") => "恢复",
            ("ja", "Delete") => "削除",
            ("en", "Delete") => "Delete",
            (_, "Delete") => "删除",
            ("ja", "Close") => "閉じる",
            ("en", "Close") => "Close",
            (_, "Close") => "关闭",
            ("ja", "RestoreConfirmTitle") => "クラウドアーカイブから復元しますか？",
            ("en", "RestoreConfirmTitle") => "Restore from cloud archive?",
            (_, "RestoreConfirmTitle") => "从云存档恢复？",
            ("ja", "RestoreConfirm") => "現在のローカルデータは復元前に安全バックアップされ、その後このクラウドアーカイブで置き換えられます。",
            ("en", "RestoreConfirm") => "Current local data will be safety-backed up before it is replaced by this cloud archive.",
            (_, "RestoreConfirm") => "当前本地数据会先生成安全备份，随后由所选云存档替换。",
            ("ja", "DeleteConfirmTitle") => "クラウドアーカイブを削除しますか？",
            ("en", "DeleteConfirmTitle") => "Delete cloud archive?",
            (_, "DeleteConfirmTitle") => "删除云存档？",
            ("ja", "DeleteConfirm") => "この操作はリモートの {0} を削除します。元に戻せません。",
            ("en", "DeleteConfirm") => "This permanently deletes {0} from the remote server.",
            (_, "DeleteConfirm") => "这将永久删除远端文件 {0}，无法撤销。",
            ("ja", "RestoreSuccess") => "クラウドアーカイブから復元しました。",
            ("en", "RestoreSuccess") => "Cloud archive restored successfully.",
            (_, "RestoreSuccess") => "已从云存档成功恢复。",
            ("ja", "DeleteSuccess") => "クラウドアーカイブを削除しました。",
            ("en", "DeleteSuccess") => "Cloud archive deleted.",
            (_, "DeleteSuccess") => "云存档已删除。",
            ("ja", "HttpWarning") => "HTTP 接続では認証情報が暗号化されません。HTTPS の使用を推奨します。",
            ("en", "HttpWarning") => "HTTP does not encrypt WebDAV credentials. HTTPS is strongly recommended.",
            (_, "HttpWarning") => "HTTP 不会加密 WebDAV 凭据，强烈建议使用 HTTPS。",
            _ => key
        };
    }

    public static string Format(string language, string key, params object[] args) => string.Format(CultureInfo.CurrentCulture, Get(language, key), args);

    public static string StatusText(string language, CloudBackupStatus status, string? errorCode) =>
        Format(language, "OperationFailed", string.IsNullOrWhiteSpace(errorCode) ? status.ToString() : $"{status} / {errorCode}");
}
